### ISSUE TITLE
Resource creation failed using CFT for a new VPC

### ISSUE THREAD

**Issue by devarshishah3** [aws-quickstart/quickstart-hashicorp-consul#69]
Seeing the following error:
Embedded stack arn:aws:cloudformation:us-east-1:953326910892:stack/HashiCorp-Consul-HashiCorpConsulStack-X2BVTTO5RYTL/4a55bf80-f3c2-11ea-a21e-0e8805686543 was not successfully created: The following resource(s) failed to create: [ConfigureSSLStack, ConsulServerProfile, ConsulClientProfile].

**Comment by gargana** [comment]
Hi Devarshishah3

In order to find out the actual failure was we will need to look into the events for the nested stack "arn:aws:cloudformation:us-east-1:953326910892:stack/HashiCorp-Consul-HashiCorpConsulStack-X2BVTTO5RYTL/4a55bf80-f3c2-11ea-a21e-0e8805686543".

The best way to do this is typically to turn off the "Rollback on failure" behavior.

On the third step launching the Quick Start you will see a heading "Advanced Options" and under that "Stack creation options".  Under "Rollback on failure" select "Disabled".

If the stack fails to launch the nested stack will be available to inspect.

One can also inspect "Failed" or "Deleted" stacks by toggling the filter on the CloudFormation stack dashboard from "Active" to "Failed" or "Deleted".

Once you have those events from the nested stack I can assist further.
